### PR TITLE
feature requests 1.3.0 release

### PR DESCRIPTION
**Pull request by oliveregger**
* [#74](https://github.com/ahdis/ch-elm/issues/74): Check for BER and UIDB format
* [#77](https://github.com/ahdis/ch-elm/issues/77): VCT and HIV Codes for patient (guidance)

### CODE REVIEW

**Comment by oliveregger** [comment]
https://build.fhir.org/ig/ahdis/ch-elm/branches/oe_130work/qa.html

**Comment by oliveregger** [comment]
@ziegm: can we do something with the warning 	The modifier extension http://hl7.org/fhir/1.0/StructureDefinition/extension-ConceptMap.element.target.equivalence from FHIR version 1.0 is not allowed to be used at this point (allowed = e:ConceptMap.element.target; this element is [[BackboneElement, ConceptMap.group.element.target]; this is a warning since contexts may be renamed between FHIR versions)

**Comment by ziegm** [comment]
> @ziegm: can we do something with the warning The modifier extension http://hl7.org/fhir/1.0/StructureDefinition/extension-ConceptMap.element.target.equivalence from FHIR version 1.0 is not allowed to be used at this point (allowed = e:ConceptMap.element.target; this element is [[BackboneElement, ConceptMap.group.element.target]; this is a warning since contexts may be renamed between FHIR versions)

We had the message already suppressed (with a link to zulip), but it changed in the wording. I updated it.

**Comment by ziegm** [comment]
@oliveregger maybe add a description what VCT stands for (in guidance)?

**Comment by oliveregger** [comment]
> @oliveregger maybe add a description what VCT stands for (in guidance)?

will be taken over by FOPH, probably no explanation needed

**Pull request merged**
